version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django_backend
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      django_net:
        ipv4_address: 172.25.0.10

  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      django_net:
        ipv4_address: 172.25.0.5

volumes:
  pgdata:

networks:
  django_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
